[project]
name = "life4-dashboard"
version = "0.1.0"
description = "Life4 Dashboard Application"
authors = [
    { name = "Cole Juracek"}
]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.10.4",
    "requests>=2.32.5",
    "streamlit>=1.62",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
    "pre-commit>=4.0.1",
    "pytest>=9.1.1",
]
